# fly.toml app configuration file generated for opossum-bot on 2024-10-11T08:28:30-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'opossum-bot'
primary_region = 'iad'

[build]
  dockerfile = "Dockerfile"

[build.args]
  BUILD_ENV = "production"

[experimental]
  auto_rollback = true
  enable_consul = true

# Removed [http_service] block since the bot does not handle HTTP requests

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
