name: Deploy Website to Fly.io

on:
  push:
    branches:
      - main
    paths:
      - 'website/**'
      - '.github/workflows/deploy_website.yml'

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      cache-hit: ${{ steps.cache-deps.outputs.cache-hit }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    - name: Cache Website dependencies
      id: cache-deps
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-website-${{ hashFiles('website/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-website-
    - name: Install dependencies
      if: steps.cache-deps.outputs.cache-hit != 'true'
      run: |
        python -m pip install --upgrade pip
        pip install --no-cache-dir -r website/requirements.txt

  build:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: ./website
        push: false
        tags: opossum-website:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

  deploy:
    needs: build
    runs-on: ubuntu-latest
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Fly.io CLI
      uses: superfly/flyctl-actions/setup-flyctl@master
    - name: Deploy Website
      run: |
        cd website
        flyctl deploy --remote-only
