name: Deploy to Fly.io

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Cache Python dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r bot/requirements.txt
        pip install -r website/requirements.txt

    - name: Set up Fly.io CLI
      uses: superfly/flyctl-actions/setup-flyctl@master

    - name: Deploy Bot
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      run: |
        cd bot
        flyctl deploy --remote-only

    - name: Deploy Website
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      run: |
        cd website
        flyctl deploy --remote-only

    - name: Update Bot Version
      run: |
        NEW_VERSION=$(date +%Y.%m.%d.%H%M)
        flyctl secrets set BOT_VERSION=$NEW_VERSION -a opossum-bot
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
