name: Deploy Bot to Fly.io

on:
  push:
    branches:
      - main
    paths:
      - 'bot/**'
      - '.github/workflows/deploy_bot.yml'
      

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      cache-hit: ${{ steps.cache-deps.outputs.cache-hit }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    - name: Cache Bot dependencies
      id: cache-deps
      uses: actions/cache@v5
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-bot-${{ hashFiles('bot/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-bot-
    - name: Install dependencies
      if: steps.cache-deps.outputs.cache-hit != 'true'
      run: |
        python -m pip install --upgrade pip
        pip install --no-cache-dir -r bot/requirements.txt

  build:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v4
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: ./bot
        push: false
        tags: opossum-bot:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

  deploy:
    needs: build
    runs-on: ubuntu-latest
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Fly.io CLI
      uses: superfly/flyctl-actions/setup-flyctl@master
    - name: Deploy Bot
      run: |
        cd bot
        flyctl deploy --remote-only
    - name: Update Bot Version
      run: |
        NEW_VERSION=$(date +%Y.%m.%d.%H%M)
        flyctl secrets set BOT_VERSION=$NEW_VERSION -a opossum-bot