name: Deploy Website to Fly.io

on:
  push:
    branches:
      - main
    paths:
      - 'website/**'
      - '.github/workflows/deploy_website.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Cache Website dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-website-${{ hashFiles('website/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-website-
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --no-cache-dir -r website/requirements.txt
    - name: Set up Fly.io CLI
      uses: superfly/flyctl-actions/setup-flyctl@master
    - name: Deploy Website
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      run: |
        cd website
        flyctl deploy --remote-only
